### PR TITLE
Update LICENSE.rst

### PR DESCRIPTION
**Pull request by Nozlaf**
numbering was wrong on your licence where it says you cannot fork it

so i've forked it and creating a pull request to fix it..

### CODE REVIEW

**Comment by ericloyd** [comment]
I have reviewed these changes and believe them to be accurate, but I am not certain about the change made to line 23.  I fail to see how that solves the problem.

**Comment by jhomann** [comment]
Yeah it's really bad phrasing. It's probably about time to bring that up again, it should really state that differently since a fork in the git world is not really a bad thing. Essentially the license is doing a roundabout way of saying "don't fork this and redistribute it as your own / for profit" so there is nothing wrong with forking it to make changes etc here on Github.

**Comment by Nozlaf** [comment]
in relation to line 23, its just github for some reason claiming that i removed the paragraph and re-added it,  probably because I edited it on the website instead of actually syncing

**Comment by jhomann** [comment]
Since that whole paragraph is on a single line, it may have changed the file ending on a newline or something too, which would show up as a whole line change. No problem.

**Comment by ericloyd** [comment]
If the line hasn't been changed, then it should be removed from the change record.  I fail to see how it improves the UX or functionality if it is replaced with an exact duplicate.  After all, according to the ship of Thesues paradox, if I replace every plank of a ship with new wood, is it still the same ship?  


Okay, okay, I'm just dragging this out (including my original post because I'm giving @Nozlaf a hard time).

**Comment by box293** [comment]
It's ship++

**Comment by ericloyd** [comment]
Bullship.

**Pull request merged**
