### PR TITLE
Issues #638, #660, #653, #648, #670

### PR DESCRIPTION
**Pull request by ccztux**
This pull request addresses and fixes the issues: #638, #660, #653, #648, #670 

- In case ```ncpa_listener``` is working in dual stack mode (IPv4 and IPv6), IPv4-mapped IPv6 addresses have not matched IPv4 addresses used in ```allowed_hosts```
- allowed_hosts doenst support hostnames
- ncpa_listener fails to start when IPv6 is disabled.
- an exception throwed in one api endpoint breaks the whole api

### CODE REVIEW

**Comment by ccztux** [comment]
@jomann09
I would like to replace the IPv4-mapped IPv6 addresses in ```ncpa_listener.log``` too, but i dont know, where to do this. Can you help me with this?

**Comment by jomann09** [comment]
Can you give an example of the output that you're talking about in the `ncpa_listener.log` that you are talking about?

Also sorry about being busy I haven't had a chance to look through and merge these. I'm going to be working on some NCPA the next couple weeks so I will get to it soon.

**Comment by ccztux** [comment]
After long consideration i think it would be better to use the IPv4-mapped IPv6 addresses everywhere. In the ncpa_listener.log and also in the web interface. So i will revert my change in database.py.
This IPv4-mapped IPv6 addresses let you know, that ncpa_listener is running in dual stack mode.
I think it is a good idea to use IPv4 as default, as mentioned here: https://github.com/NagiosEnterprises/ncpa/issues/648#issue-647552335

**Comment by ccztux** [comment]
FYI: I am also working on #653 in this pull request.

**Comment by ccztux** [comment]
After many builds and testing i ask you for review and testing.

**Comment by ccztux** [comment]
@jomann09 Sorry for this weird pull request. Normally i make one pull request per issue. If you like i can split this pull request into multiple.

**Comment by jomann09** [comment]
This actually looks fine, I'm looking through the code now and should be able to merge it into maint just fine.

**Comment by jomann09** [comment]
Merging this, due to some changes to the allowed_hosts we will be setting this up as a 2.3.0 release. I'm going to go through the issues you fixed while it's in maint branch and close each of the issues that it relates to. I'm going to go through the issues for anything else that needs to get into 2.3.0.

**Pull request merged**
